[package]
name = "polars-ops"
version = "0.21.1"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/pola-rs/polars"
description = "More operations on polars data structures"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars-arrow = { version = "0.21.1", path = "../polars-arrow", default-features = false }
polars-core = { version = "0.21.1", path = "../polars-core", features = ["private"], default-features = false }

[features]
dtype-categorical = ["polars-core/dtype-categorical"]
dtype-date = ["polars-core/dtype-date"]
dtype-datetime = ["polars-core/dtype-datetime"]
dtype-time = ["polars-core/dtype-time"]
dtype-duration = ["polars-core/dtype-duration"]
dtype-struct = ["polars-core/dtype-struct"]
dtype-u8 = ["polars-core/dtype-u8"]
object = ["polars-core/object"]
to_dummies = []
list_to_struct = ["polars-core/dtype-struct", "list"]
list = []
diff = []
strings = []
