[files]
extend-exclude = [
  ".git/",
  "*.csv",
  "*.gz",
  "dists.dss",
  "**/images/*",
]
ignore-hidden = false

[default]
extend-ignore-re = [
  '"Theatre": \[.+\],',
]

[default.extend-words]
arange = "arange"
ser = "ser"
splitted = "splitted"
strat = "strat"

[type.py.extend-identifiers]
ba = "ba"
ody = "ody"

[type.rust.extend-identifiers]
ANDed = "ANDed"
bck = "bck"
Fo = "Fo"
ND = "ND"
nd = "nd"
NDJson = "NDJson"
NDJsonSinkNode = "NDJsonSinkNode"
NDJsonReadOptions = "NDJsonReadOptions"
opt_nd = "opt_nd"
