[default]
extend-ignore-identifiers-re = [
  "splitted.*",
]

[default.extend-identifiers]
bck = "bck"
Fo = "Fo"
ND = "ND"
ba = "ba"
nd = "nd"
opt_nd = "opt_nd"
ANDed = "ANDed"
ody = "ody"

[default.extend-words]
arange = "arange"
strat = "strat"
'"r0ot"' = "r0ot"
wee = "wee"
ser = "ser"
ND = "ND"
ody = "ody"

[type.csv]
extend-glob = ["*.csv"]
check-file = false

[type.gz]
extend-glob = ["*.gz"]
check-file = false

[files]
extend-exclude = ["_typos.toml", "dists.dss"]
