[package]
name = "polars-row"
version = "0.29.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/pola-rs/polars"
description = "Row encodings for the Polars DataFrame library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow.workspace = true
polars-error = { version = "0.29.0", path = "../polars-error" }
polars-utils = { version = "0.29.0", path = "../polars-utils" }
