[package]
name = "polars-json"
version = "0.29.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash.workspace = true
arrow.workspace = true
hashbrown.workspace = true
num-traits.workspace = true
polars-arrow = { version = "0.29.0", path = "../polars-arrow", default-features = false }
polars-error = { version = "0.29.0", path = "../polars-error" }
polars-utils = { version = "0.29.0", path = "../polars-utils" }
simd-json = { version = "0.9", features = ["allow-non-simd", "known-key"] }
fallible-streaming-iterator = "0.1"
