[package]
name = "polars-utils"
version.workspace = true
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2021"
license = "MIT"
description = "private utils for the polars dataframe library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash.workspace = true
hashbrown.workspace = true
num-traits.workspace = true
once_cell.workspace = true
polars-error = { version = "0.31.1", path = "../polars-error" }
rayon.workspace = true
smartstring.workspace = true
sysinfo = { version = "0.29", default-features = false, optional = true }

[features]
bigidx = []
nightly = []
