[package]
name = "aggregate_multiple_files_in_chunks"
version = "0.1.0"
authors = ["Adri√°n Gallego Castellanos <kugoad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
polars = { path = "../../polars" }
rayon = "1.5"
