[package]
name = "polars-row"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Row encodings for the Polars DataFrame library"

[dependencies]
bitflags = { workspace = true }
bytemuck = { workspace = true }
polars-compute = { workspace = true, features = ["cast"] }
polars-dtype = { workspace = true }
polars-error = { workspace = true }
polars-utils = { workspace = true }

arrow = { workspace = true }

[dev-dependencies]
arrow = { workspace = true, features = ["proptest"] }
proptest = { workspace = true }

[lints]
workspace = true
