[package]
name = "polars-parquet"
version = { workspace = true }
authors = [
  "Jorge C. Leitao <jorgecarleitao@gmail.com>",
  "Apache Arrow <dev@arrow.apache.org>",
  "Ritchie Vink <ritchie46@gmail.com>",
]
edition = { workspace = true }
homepage = { workspace = true }
license = "MIT AND Apache-2.0"
repository = { workspace = true }
description = "Apache Parquet I/O operations for Polars"

[dependencies]
ahash = { workspace = true }
arrow = { workspace = true, features = ["io_ipc"] }
base64 = { workspace = true }
bytemuck = { workspace = true }
ethnum = { workspace = true }
fallible-streaming-iterator = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
num-traits = { workspace = true }
polars-compute = { workspace = true }
polars-error = { workspace = true }
polars-utils = { workspace = true, features = ["mmap"] }
simdutf8 = { workspace = true }

parquet-format-safe = "0.2"
streaming-decompression = "0.1"

async-stream = { version = "0.3.3", optional = true }

brotli = { version = "^6.0", optional = true }
flate2 = { workspace = true, optional = true }
lz4 = { version = "1.24", optional = true }
lz4_flex = { version = "0.11", optional = true }
serde = { workspace = true, optional = true }
snap = { version = "^1.1", optional = true }
zstd = { version = "^0.13", optional = true, default-features = false }

xxhash-rust = { version = "0.8", optional = true, features = ["xxh64"] }

[dev-dependencies]
rand = "0.8"

[features]
compression = [
  "zstd",
  "gzip",
  "snappy",
  "lz4",
  "brotli",
]

# compression backends
snappy = ["snap"]
gzip = ["flate2/rust_backend"]
gzip_zlib_ng = ["flate2/zlib-ng"]
lz4 = ["dep:lz4"]
lz4_flex = ["dep:lz4_flex"]

async = ["async-stream", "futures", "parquet-format-safe/async"]
bloom_filter = ["xxhash-rust"]
serde_types = ["serde"]
