[package]
name = "polars-time"
version = "0.1.1"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Time related code for the polars dataframe library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
polars-arrow = { version = "0.19.0", path = "../polars-arrow", features = ["compute"] }
polars-core = { version = "0.19.0", path = "../polars-core", features = ["temporal", "dtype-date", "dtype-datetime"] }

[features]
dtype-date = []
dtype-datetime = []
private = []

default = ["private"]
