[package]
name = "polars-time"
version = "0.24.1"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Time related code for the polars dataframe library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
chrono-tz = { version = "0.6", optional = true }
lexical = { version = "6", default-features = false, features = ["std", "parse-floats", "parse-integers"] }
polars-arrow = { version = "0.24.1", path = "../polars-arrow", features = ["compute", "temporal"] }
polars-core = { version = "0.24.1", path = "../polars-core", default-features = false, features = ["private", "dtype-datetime", "dtype-duration", "dtype-time", "dtype-date"] }
polars-utils = { version = "0.24.1", path = "../polars-utils" }
serde = { version = "1", features = ["derive"], optional = true }

[features]
dtype-date = ["polars-core/dtype-date", "polars-core/temporal"]
dtype-datetime = ["polars-core/dtype-date", "polars-core/temporal"]
dtype-time = ["polars-core/dtype-time", "polars-core/temporal"]
dtype-duration = ["polars-core/dtype-duration", "polars-core/temporal"]
rolling_window = ["polars-core/rolling_window", "dtype-duration"]
private = []
fmt = ["polars-core/fmt"]
timezones = ["chrono-tz"]

test = [
  "dtype-date",
  "dtype-datetime",
  "polars-core/fmt",
]

default = ["private"]
