[package]
name = "plugin_v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "plugin_v1"
crate-type = ["cdylib"]

[dependencies]
arrow = { workspace = true, default-features = false }
num = "*"
polars = { workspace = true, features = ["timezones", "allow_unused", "ffi_plugin"] }
pyo3 = { workspace = true }
pyo3-polars = { workspace = true, features = ["derive", "ffi_plugin"] }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
