name: Benchmark

on:
  pull_request:
    paths:
      - 'polars/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-23
          override: true
          components: rustfmt, clippy
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        shell: bash
        run: |
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3' # The R version to download (if necessary) and use.
      - run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m venv venv
          source venv/bin/activate
          pip install -r py-polars/build.requirements.txt
          cd py-polars
          rustup override set nightly-2022-03-23 && RUSTFLAGS="-C embed-bitcode" maturin develop --rustc-extra-args="-C codegen-units=8 -C lto=thin -C target-cpu=native" --release
          cd tests/db-benchmark
          Rscript -e 'install.packages("data.table", repos="https://Rdatatable.github.io/data.table")'
          Rscript groupby-datagen.R 1e7 1e2 5 0
          echo "LAZY vs EAGER tests"
          python lazy_vs_eager.py
          echo "run various.py tests"
          python various.py
          echo "ON STRINGS"
          python main.py on_strings
          echo "ON CATEGORICALS"
          python main.py

