name: Benchmark

on:
  pull_request:
    paths:
      - 'polars/**'
      - 'py-polars/tests/db-benchmark/**'
      - '.github/workflows/benchmark.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3'
      - name: Run benchmark tests
        env:
          RUSTFLAGS: -C embed-bitcode
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m venv venv
          source venv/bin/activate
          pip install -r py-polars/build.requirements.txt
          cd py-polars
          maturin develop --release -- -C codegen-units=8 -C lto=thin -C target-cpu=native
          cd tests/db-benchmark
          Rscript -e 'install.packages("data.table", repos="https://Rdatatable.github.io/data.table")'
          Rscript groupby-datagen.R 1e7 1e2 5 0
          echo "LAZY vs EAGER tests"
          python lazy_vs_eager.py
          echo "run various.py tests"
          python various.py
          echo "ON STRINGS"
          python main.py on_strings
          echo "ON CATEGORICALS"
          python main.py

