name: Build and test Rust

on:
  pull_request:
    paths:
      - polars/**
      - examples/**
      - .github/workflows/build-test-rust.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup override set stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Use sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run cargo check
        working-directory: examples
        run: cargo check

  features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Use sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install dependencies
        run: cargo install cargo-hack

      - name: Run cargo hack
        working-directory: polars
        run: cargo hack check --each-feature --no-dev-deps --features private

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: polars

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup component add rustfmt clippy miri

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: polars

      - name: Use sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run : |
          cargo clippy --all-features \
            -p polars-core \
            -p polars-io \
            -p polars-lazy \
            -- -D warnings
          cargo clippy -- -D warnings

      - name: Run miri
        run: |
          cargo miri setup
          cargo clean
          make miri

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: polars

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: polars

      - name: Use sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run tests
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: make test

      - name: Run integration tests
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: make integration-tests
