name: Deploy Rust documentation

on:
  push:
    branches:
      - master
    paths:
      - polars/**
      - .github/workflows/docs-deploy-rust.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-03-10
          components: rust-docs

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build Rust documentation
        env:
          RUSTDOCFLAGS: --cfg docsrs
        run: cargo doc --features=docs-selection --package polars

      - name: Create redirect to Polars crate and set no-jekyll
        run: |
          echo '<meta http-equiv=refresh content=0;url=polars/index.html>' > target/doc/index.html
          touch target/doc/.nojekyll

      - name: Deploy Rust docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
          clean-exclude: py-polars/**

      # Make sure documentation artifacts are not cached
      - name: Clean up documentation artifacts
        run: rm -rf target/doc
