name: Deploy documentation

on:
  push:
    tags:
      - '**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'py-polars/docs/requirements-docs.txt'

      - name: Install Python dependencies
        working-directory: py-polars/docs
        run: |
          pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Build Python documentation
        working-directory: py-polars/docs
        run: make html

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-02-14
          components: rust-docs

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build Rust documentation
        env:
          RUSTDOCFLAGS: --cfg docsrs
        run: cargo doc --features=docs-selection --package polars

      - name: Prepare deployment
        run: |
          echo '<meta http-equiv=refresh content=0;url=polars/index.html>' > target/doc/index.html
          mkdir target/doc/py-polars
          mv py-polars/docs/build/html target/doc/py-polars

      - name: Deploy
        run: |
          ghp-import -n target/doc
          git push -qf https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git gh-pages

      # Make sure documentation artifacts are not cached
      - name: Clean up documentation artifacts
        run: rm -rf target/doc
