name: Build Python documentation

on:
  pull_request:
    paths:
      - py-polars/docs/**
      - py-polars/polars/**
      - .github/workflows/docs-python.yml
  push:
    branches:
      - main
    paths:
      - py-polars/docs/**
      - py-polars/polars/**
      - .github/workflows/docs-python.yml
    tags:
      - py-**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-python-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: py-polars/docs/requirements-docs.txt

      - name: Install Python dependencies
        working-directory: py-polars/docs
        run: pip install -r requirements-docs.txt

      - name: Build Python documentation
        working-directory: py-polars/docs
        env:
          SPHINXOPTS: -W --jobs=auto
        run: make html

      - name: Deploy Python docs for latest development version
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: py-polars/docs/build/html
          target-folder: py-polars/dev

      - name: Deploy Python docs for latest release version
        if: ${{ github.ref_type == 'tag' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: py-polars/docs/build/html
          # Keeping the html subfolder here for backwards compatibility
          target-folder: py-polars/html
