name: Check formatting

on:
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-fmt-all:
    name: Test global formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          curl -fsSLO https://github.com/dprint/dprint/releases/download/0.18.2/dprint-x86_64-unknown-linux-gnu.zip
          unzip -o dprint-x86_64-unknown-linux-gnu.zip dprint -d ~/.cargo/bin/
          rm -f dprint-x86_64-unknown-linux-gnu.zip
      - name: Run formatting checks
        run: |
          dprint check
