name: Windows tests rust

on:
  pull_request:
    paths:
      - 'polars/**'
      - '.github/workflows/test-windows.yaml'
jobs:
  test-rust:
    runs-on: windows-latest
    steps:
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-22
          override: true
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: |
          set RUSTFLAGS="-C debuginfo=0"
          cd polars && make test && make integration-tests
