name: Test Python

on:
  pull_request:
    paths:
      - 'py-polars/**'
      - 'polars/**'
      - '.github/workflows/test-python.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7', '3.10']
    defaults:
      run:
        working-directory: py-polars

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'py-polars/requirements-dev.txt'
      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "$GITHUB_WORKSPACE/py-polars/venv/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      # Allow untyped calls for older Python versions
      - name: Run mypy
        run: mypy ${{ (matrix.python-version == '3.7') && '--allow-untyped-calls' || '' }}
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-08-22
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: py-polars
      - name: Install Polars
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          source activate
          maturin develop
      - name: Run tests and report coverage
        run: pytest --cov=polars
      - name: Run doctests
        run: python tests/docs/run_doc_examples.py
      - name: Check import without optional dependencies
        run: |
          pip uninstall pandas -y
          python -c 'import polars'
          pip uninstall numpy -y
          python -c 'import polars'
          pip uninstall pyarrow -y
          python -c 'import polars'
