name: Windows tests rust

on:
  pull_request:
    paths:
      - 'polars/**'
      - '.github/workflows/test-windows.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-rust:
    runs-on: windows-latest
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        working-directory: polars
        run: make test && make integration-tests
