name: Test JS
on:
  pull_request:
    paths:
      - 'nodejs-polars/**'
jobs: 
  test-js: 
    runs-on: ubuntu-latest
    name:  "${{ matrix.os }} node:${{ matrix.node }}"
    defaults:
      run:
        working-directory: nodejs-polars
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        node: ["16", "17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: nodejs-polars/yarn.lock
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-23
          override: true
          components: rustfmt, clippy
      - run: yarn --version
      - name: Install Node Dependencies
        run: yarn install
      - name: Build Binary
        run: yarn build:debug
      - name: Run Linting
        run: yarn lint:ts
      - name: Run Tests
        run: yarn test
      - name: Build JS
        run: yarn build:ts
