name: Test python

on:
  pull_request:
    paths:
      - 'py-polars/**'
      - 'polars/**'
      - '.github/workflows/test-python.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-python:
    name: Build and test Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7', '3.10']
    defaults:
      run:
        working-directory: py-polars

    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-08-22
          components: rustfmt, clippy
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build.requirements.txt
      - name: Run formatting checks
        run: |
          black --check .
          blackdoc --check .
          isort --check .
          pyupgrade --py37-plus `find . -name "*.py" -type f`
          rustup override set nightly-2022-08-22 && cargo fmt --all -- --check
      - name: Run linting
        run: flake8
      # Allow untyped calls for older Python versions
      - name: Run type checking
        run: mypy  ${{ (matrix.python-version == '3.7') && '--allow-untyped-calls' || '' }}
      - name: Run tests
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          rustup override set nightly-2022-08-22 && make venv && make test-with-cov
          make clippy
      - name: Check doc examples
        run: make doctest
      # test if we can import polars without any requirements
      - name: Import polars
        run: |
          pip uninstall pandas -y
          python -c "import polars"
          pip uninstall numpy -y
          python -c "import polars"
          pip uninstall pyarrow -y
          python -c "import polars"
